# Guest image list for TGOS images (v0.0.15)

[[images]]
name = "initramfs-aarch64-busybox.cpio.gz"
version = "0.0.15"
description = "BusyBox initramfs for aarch64"
sha256 = "7ed7c3123d981c7c4959b83e0864dbb03f9e5b54584d50ceec83954b965c7863"
arch = "aarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.15/initramfs-aarch64-busybox.cpio.gz.tar.xz"
released_at = "2026-10-09T02:50:33Z"

[[images]]
name = "initramfs-loongarch64-busybox.cpio.gz"
version = "0.0.15"
description = "BusyBox initramfs for loongarch64"
sha256 = "29a8b8c440464e51e236ff5abaadb0a2540eedf3e8f306ba3f04de49bc7c2beb"
arch = "loongarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.15/initramfs-loongarch64-busybox.cpio.gz.tar.xz"
released_at = "2026-10-09T02:51:12Z"

[[images]]
name = "initramfs-riscv64-busybox.cpio.gz"
version = "0.0.15"
description = "BusyBox initramfs for riscv64"
sha256 = "99e0e43ecbb0551fd27d4bf15e2ad5c20f945e0013308ec1bee3b5f30f4a5f17"
arch = "riscv64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.15/initramfs-riscv64-busybox.cpio.gz.tar.xz"
released_at = "2026-10-09T02:51:17Z"

[[images]]
name = "initramfs-x86_64-busybox.cpio.gz"
version = "0.0.15"
description = "BusyBox initramfs for x86_64"
sha256 = "903c06cab0b9aad6bcb1e46d3234dd5bc9f1206b7ac5521b5551c5b6ae337059"
arch = "x86_64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.15/initramfs-x86_64-busybox.cpio.gz.tar.xz"
released_at = "2026-10-09T02:51:22Z"

[[images]]
name = "orangepi-5-plus.img"
version = "0.0.15"
description = "Bootable disk image for Orange Pi development board"
sha256 = "6fdba10e0b04edbcad236d6902e54b2a4026c52840fbe4ec14f8177157b7079e"
arch = "aarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.15/orangepi-5-plus.img.tar.xz"
released_at = "2026-10-09T03:03:13Z"

[[images]]
name = "orangepi-5-plus-starry"
version = "0.0.15"
description = "StarryOS for Orange Pi development board"
sha256 = "ff7f072dc24aac23bfb7d164130749a113915941df1342fde291604f28b21e26"
arch = "aarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.15/orangepi-5-plus-starry.tar.xz"
released_at = "2026-10-09T03:58:20Z"

[[images]]
name = "orangepi"
version = "0.0.15"
description = "Guest image bundle for Orange Pi development board"
sha256 = "198a132fa4a79a9e087c21ffb1f9d24f60d6422d0088312815f01e339bf46ddb"
arch = "aarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.15/orangepi.tar.xz"
released_at = "2026-10-09T03:58:06Z"

[[images]]
name = "phytiumpi"
version = "0.0.15"
description = "Guest image bundle for Phytium Pi development board"
sha256 = "8492c5ab073af12afe180f72ca43057a95ba96bb3fe1718580ba8f3f7b58ac00"
arch = "aarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.15/phytiumpi.tar.xz"
released_at = "2026-10-09T03:59:27Z"

[[images]]
name = "qemu-aarch64"
version = "0.0.15"
description = "Guest image bundle for QEMU aarch64 virtualization"
sha256 = "d13635d011dd6911ea630669f687c1df1e25d0f2a66d5750ef4a2960931437e8"
arch = "aarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.15/qemu-aarch64.tar.xz"
released_at = "2026-10-09T04:00:09Z"

[[images]]
name = "qemu-loongarch64"
version = "0.0.15"
description = "Guest image bundle for QEMU LoongArch64 virtualization"
sha256 = "10471c9d760ff7040246885d367e8a3924d0c3cb85cc31dce385063a94994e12"
arch = "loongarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.15/qemu-loongarch64.tar.xz"
released_at = "2026-10-09T04:01:13Z"

[[images]]
name = "qemu-riscv64"
version = "0.0.15"
description = "Guest image bundle for QEMU riscv64 virtualization"
sha256 = "0ac73d1051d6c680aa6cf6782dcedd6cc77b9e7b85623c5e27666cab97b62046"
arch = "riscv64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.15/qemu-riscv64.tar.xz"
released_at = "2026-10-09T04:01:25Z"

[[images]]
name = "qemu-x86_64"
version = "0.0.15"
description = "Guest image bundle for QEMU x86_64 virtualization"
sha256 = "39b519b6669bbc86b5ddf530ad89bb3bc929ccd41df9c8ad1a034a4600eaca90"
arch = "x86_64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.15/qemu-x86_64.tar.xz"
released_at = "2026-10-09T04:01:30Z"

[[images]]
name = "rootfs-aarch64-alpine.img"
version = "0.0.15"
description = "Alpine rootfs image for aarch64"
sha256 = "5be29b7c4dd5c4af07c492c257b085fa3c257ec7466d84a2cadec4a5858f3e48"
arch = "aarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.15/rootfs-aarch64-alpine.img.tar.xz"
released_at = "2026-10-09T03:20:38Z"

[[images]]
name = "rootfs-aarch64-busybox.img"
version = "0.0.15"
description = "BusyBox rootfs image for aarch64"
sha256 = "e73c21dc37b70bf7416df55c9551c21ad4745beb07487e08bc7bcdb498c978cb"
arch = "aarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.15/rootfs-aarch64-busybox.img.tar.xz"
released_at = "2026-10-09T03:22:23Z"

[[images]]
name = "rootfs-aarch64-debian.img"
version = "0.0.15"
description = "Debian rootfs image for aarch64"
sha256 = "4852fdc25326d929ea4f5100c1feafbeb1dc9bff155e345821aaf5cb9350417b"
arch = "aarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.15/rootfs-aarch64-debian.img.tar.xz"
released_at = "2026-10-09T03:26:52Z"

[[images]]
name = "rootfs-aarch64-orangepi-jammy.img"
version = "0.0.15"
description = "orangepi-jammy rootfs image for aarch64"
sha256 = "02d86e6e16ac3487005e48d15285dcff0eef074021e588bb6e84c6203c449107"
arch = "aarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.15/rootfs-aarch64-orangepi-jammy.img.tar.xz"
released_at = "2026-10-09T03:37:13Z"

[[images]]
name = "rootfs-loongarch64-alpine.img"
version = "0.0.15"
description = "Alpine rootfs image for loongarch64"
sha256 = "91e4ef97675897b183d8df68565548f304de85e724a75498e5985ed29a1f7918"
arch = "loongarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.15/rootfs-loongarch64-alpine.img.tar.xz"
released_at = "2026-10-09T03:40:31Z"

[[images]]
name = "rootfs-loongarch64-busybox.img"
version = "0.0.15"
description = "BusyBox rootfs image for loongarch64"
sha256 = "7ad1a227cafe0ce6ffed05c268bb702ce7b16ccab8013fb1b578f2d2068c9c91"
arch = "loongarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.15/rootfs-loongarch64-busybox.img.tar.xz"
released_at = "2026-10-09T03:41:57Z"

[[images]]
name = "rootfs-riscv64-alpine.img"
version = "0.0.15"
description = "Alpine rootfs image for riscv64"
sha256 = "c6b7cee468ca3b0637c472d3ce07482e55eee7ad7d59f2ce871ffc882c214bf8"
arch = "riscv64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.15/rootfs-riscv64-alpine.img.tar.xz"
released_at = "2026-10-09T03:44:08Z"

[[images]]
name = "rootfs-riscv64-busybox.img"
version = "0.0.15"
description = "BusyBox rootfs image for riscv64"
sha256 = "1ce5e6961db9bd924da74b2293b32e7cc879c0bccb396429bcaf269e2af4abcc"
arch = "riscv64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.15/rootfs-riscv64-busybox.img.tar.xz"
released_at = "2026-10-09T03:44:52Z"

[[images]]
name = "rootfs-riscv64-debian.img"
version = "0.0.15"
description = "Debian rootfs image for riscv64"
sha256 = "b70c8ffef1eb8042bdee4861891b800dedf45d62bd3fa6aeb26f2d17d46e802c"
arch = "riscv64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.15/rootfs-riscv64-debian.img.tar.xz"
released_at = "2026-10-09T03:47:12Z"

[[images]]
name = "rootfs-x86_64-alpine.img"
version = "0.0.15"
description = "Alpine rootfs image for x86_64"
sha256 = "4a84363ba91ba88a6cc11f2ad77a6c84c7bd8fa911cd400ec194903a32c80771"
arch = "x86_64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.15/rootfs-x86_64-alpine.img.tar.xz"
released_at = "2026-10-09T03:49:25Z"

[[images]]
name = "rootfs-x86_64-busybox.img"
version = "0.0.15"
description = "BusyBox rootfs image for x86_64"
sha256 = "0315c95f682585f9f44db787b66d37c23ca0446a1d2bac7670078268f5c845cf"
arch = "x86_64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.15/rootfs-x86_64-busybox.img.tar.xz"
released_at = "2026-10-09T03:50:03Z"

[[images]]
name = "rootfs-x86_64-debian.img"
version = "0.0.15"
description = "Debian rootfs image for x86_64"
sha256 = "1d448c4c6220ef651a42d1d15b02dfb2ff542ff34802fbeec60526db2cc095c0"
arch = "x86_64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.15/rootfs-x86_64-debian.img.tar.xz"
released_at = "2026-10-09T03:53:51Z"
