#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)
ROOT_DIR=$(cd "${SCRIPT_DIR}/../.." && pwd -P)
BUILD_DIR="$(cd "${ROOT_DIR}" && mkdir -p "build" && cd "build" && pwd -P)"

# Repository URLs

# Source directories
LINUX_REPO_URL="https://github.com/torvalds/linux.git"
LINUX_REF="${LINUX_REF:-74fe02ce122a6103f207d29fafc8b3a53de6abaf}"
LINUX_SRC_DIR="${BUILD_DIR}/qemu_linux"
LINUX_PATCH_DIR="${ROOT_DIR}/patches/qemu"
AXVISOR_TOOLS_REPO_URL="${AXVISOR_TOOLS_REPO_URL:-https://github.com/arceos-hypervisor/axvisor-tools.git}"
AXVISOR_TOOLS_REF="${AXVISOR_TOOLS_REF:-main}"
AXVISOR_TOOLS_SRC_DIR="${AXVISOR_TOOLS_SRC_DIR:-${BUILD_DIR}/axvisor-tools}"
AXVISOR_TOOLS_SKIP_CHECKOUT="${AXVISOR_TOOLS_SKIP_CHECKOUT:-0}"
ROOTFS_BUILDERS=()
BUILD_ARGS=()
ROOTFS_BUILD_ARGS=()
QEMU_OUTER_FREE_SIZE=""
PLATFORM_IMAGES_DIR=""

# Display help information
usage() {
    local usage_arch="${QEMU_ARCH:-}"

    printf 'Build supported OS for QEMU with rootfs support\n'
    printf '\n'
    printf 'Usage:\n'
    if [[ -n "${usage_arch}" ]]; then
        if [[ "${usage_arch}" == "all" ]]; then
            printf '  ./build.sh platform qemu [os] [options]\n'
        else
            printf '  ./build.sh platform qemu-%s [os] [options]\n' "${usage_arch}"
        fi
    else
        printf '  scripts/qemu.sh <command> <os> [options]\n'
        printf '\n'
        printf 'Commands:\n'
        printf '  aarch64                           Build all OS targets for AArch64 architecture\n'
        printf '  x86_64                            Build all OS targets for x86_64 architecture\n'
        printf '  riscv64                           Build all OS targets for RISC-V architecture\n'
        printf '  loongarch64                       Build all OS targets for LoongArch64 architecture\n'
        printf '  all                               Build all supported architectures and OS targets\n'
        printf '  help, -h, --help                  Display this help information\n'
        printf '  clean                             Clean build output artifacts\n'
    fi
    printf '\n'
    printf 'OS Targets:\n'
    printf '  linux                             Build the Linux OS\n'
    printf '  arceos                            Build the ArceOS OS\n'
    printf '  zephyr                            Build the Zephyr guest image (aarch64 only)\n'
    printf '  freertos                          Build the FreeRTOS guest image (aarch64 only)\n'
    printf '  all                               Build all OS targets (default)\n'
    printf '  clean                             Clean build output artifacts\n'
    printf '\n'
    printf 'Options:\n'
    printf '  Other options are passed directly to the selected OS build script.\n'
    printf '  --rootfs <list>                   Override default rootfs builders (busybox,alpine,debian)\n'
    printf '                                    Default for loongarch64 is busybox,alpine\n'
    printf '  --outer-tests <list>              Tests installed in each ext4 outer image\n'
    printf '  --guest-tests <list>              Tests installed in each nested guest image\n'
    printf '  --guest-free-size <size>          Free space reserved in each nested guest image\n'
    printf '  --outer-free-size <size>          Free space reserved after platform injection\n'
    printf '\n'
    printf 'Rootfs Packaging:\n'
    printf '  * Rootfs is generated by default for build commands.\n'
    printf '  * Rootfs is not generated for help or clean commands.\n'
    printf '  * Build outputs from all selected OS targets are staged together into /guest/<os>/ inside one rootfs.\n'
    printf '  * ext4 outputs contain a nested rootfs image; platform payload is added only to the outer image.\n'
    printf '  * BusyBox initramfs receives platform payload only; nested images and guest tests are excluded.\n'
    printf '  * qemu-aarch64 Alpine rootfs also receives the Axvisor IVC Linux kernel module when available.\n'
    printf '  * Generated rootfs artifacts are stored directly under IMAGES/rootfs.\n'
    printf '\n'
    printf 'Examples:\n'
    if [[ -n "${usage_arch}" ]]; then
        if [[ "${usage_arch}" == "all" ]]; then
            printf '  ./build.sh platform qemu linux\n'
            printf '  ./build.sh platform qemu all --rootfs busybox,alpine,debian\n'
            printf '  ./build.sh platform qemu linux --guest-tests cyclictest --outer-free-size 512M\n'
        else
            printf '  ./build.sh platform qemu-%s linux\n' "${usage_arch}"
            if [[ "${usage_arch}" == "loongarch64" ]]; then
                printf '  ./build.sh platform qemu-%s all --rootfs busybox,alpine\n' "${usage_arch}"
            else
                printf '  ./build.sh platform qemu-%s all --rootfs busybox,alpine,debian\n' "${usage_arch}"
            fi
            printf '  ./build.sh platform qemu-%s linux --guest-tests cyclictest --outer-free-size 512M\n' "${usage_arch}"
        fi
    else
        printf '  scripts/qemu.sh aarch64 linux     # Build ARM64 Linux\n'
        printf '  scripts/qemu.sh x86_64 arceos     # Build x86_64 ArceOS\n'
        printf '  scripts/qemu.sh loongarch64 linux # Build LoongArch64 Linux\n'
        printf '  scripts/qemu.sh aarch64 all --rootfs busybox,alpine,debian\n'
        printf '  scripts/qemu.sh x86_64 linux --outer-tests none --guest-tests cyclictest\n'
        printf '  scripts/qemu.sh riscv64 all       # Build all OS targets for RISC-V\n'
    fi
}

linux() {
    local linux_images_dir="${PLATFORM_IMAGES_DIR}/linux"
    local image_targets=()
    local image_sources=()
    local image_outputs=()

    info "Cloning ${ARCH} Linux source repository $LINUX_REPO_URL"
    clone_repository "$LINUX_REPO_URL" "$LINUX_SRC_DIR"
    info "Checking out ${ARCH} Linux ref ${LINUX_REF}"
    checkout_ref "$LINUX_SRC_DIR" "$LINUX_REF"

    info "Applying patches..."
    apply_patches "$LINUX_PATCH_DIR" "$LINUX_SRC_DIR"

    info "Starting to build ${ARCH} Linux OS..."
    local commands=("$@")
    case "${ARCH}" in
        aarch64)
            local linux_arch="arm64"
            local cross_compile="${AARCH64_CROSS_COMPILE:-aarch64-linux-gnu-}"
            local defconfig="defconfig"
            image_sources=("arch/arm64/boot/Image")
            image_outputs=("linux-qemu")
            ;;
        riscv64)
            local linux_arch="riscv"
            local cross_compile="${RISCV64_CROSS_COMPILE:-riscv64-linux-gnu-}"
            local defconfig="defconfig"
            image_sources=("arch/riscv/boot/Image")
            image_outputs=("linux-qemu")
            ;;
        x86_64)
            local linux_arch="x86"
            local cross_compile="${X86_CROSS_COMPILE:-}"
            local defconfig="x86_64_defconfig"
            image_sources=("arch/x86/boot/bzImage")
            image_outputs=("linux-qemu")
            ;;
        loongarch64)
            local linux_arch="loongarch"
            local cross_compile="${LOONGARCH64_CROSS_COMPILE:-loongarch64-linux-gnu-}"
            local defconfig="loongson64_defconfig"
            image_targets=("vmlinuz.efi" "vmlinux.elf")
            image_sources=("arch/loongarch/boot/vmlinuz.efi" "arch/loongarch/boot/vmlinux.elf")
            image_outputs=("vmlinuz.efi" "vmlinux.elf")
            ;;
        *)
            die "Unsupported Linux architecture: ${ARCH}"
            ;;
    esac
    
    pushd "${LINUX_SRC_DIR}" >/dev/null

    # info "Cleaning Linux: make distclean"
    # make distclean || true

    if [[ "$@" != *"clean"* ]]; then
        if [[ ${#commands[@]} -eq 0 ]] || [[ "${commands[0]}" == "all" ]]; then
            info "Configuring Linux: make ARCH=${linux_arch} CROSS_COMPILE=${cross_compile} ${defconfig}"
            make ARCH="${linux_arch}" CROSS_COMPILE="${cross_compile}" "${defconfig}" || {
                local status=$?
                popd >/dev/null
                return "$status"
            }
        fi
        
        if [[ (${#commands[@]} -eq 0 || "${commands[0]}" == "all") && ${#image_targets[@]} -gt 0 ]]; then
            info "Building Linux image targets: make -j$(nproc) ARCH=${linux_arch} CROSS_COMPILE=${cross_compile} ${image_targets[*]}"
            make -j"$(nproc)" ARCH="${linux_arch}" CROSS_COMPILE="${cross_compile}" "${image_targets[@]}" || {
                local status=$?
                popd >/dev/null
                return "$status"
            }
        elif [[ ${#commands[@]} -eq 0 ]]; then
            info "Building Linux: make -j$(nproc) ARCH=${linux_arch} CROSS_COMPILE=${cross_compile}"
            make -j"$(nproc)" ARCH="${linux_arch}" CROSS_COMPILE="${cross_compile}" || {
                local status=$?
                popd >/dev/null
                return "$status"
            }
        else
            info "Building Linux: make -j$(nproc) ARCH=${linux_arch} CROSS_COMPILE=${cross_compile} ${commands[*]}"
            make -j"$(nproc)" ARCH="${linux_arch}" CROSS_COMPILE="${cross_compile}" "${commands[@]}" || {
                local status=$?
                popd >/dev/null
                return "$status"
            }
        fi
        
        popd >/dev/null

        # If it's a full build, copy the image and create the root filesystem
        if [[ ${#commands[@]} -eq 0 ]] || [[ "${commands[0]}" == "all" ]]; then
            mkdir -p "${linux_images_dir}"
            rm -f "${linux_images_dir}/linux-qemu"
            if [[ "${ARCH}" == "loongarch64" ]]; then
                rm -f "${linux_images_dir}/vmlinuz.efi" \
                      "${linux_images_dir}/vmlinux.elf" \
                      "${linux_images_dir}/qemu-loongarch64"
            fi
            local i
            for i in "${!image_sources[@]}"; do
                KIMG_PATH="${LINUX_SRC_DIR}/${image_sources[$i]}"
                [[ -f "${KIMG_PATH}" ]] || die "Kernel image not found: ${KIMG_PATH}"
                info "Copying image: ${KIMG_PATH} -> ${linux_images_dir}/${image_outputs[$i]}"
                cp -f "${KIMG_PATH}" "${linux_images_dir}/${image_outputs[$i]}"
            done
            if [[ "${ARCH}" == "loongarch64" ]]; then
                cp -f "${linux_images_dir}/vmlinux.elf" "${linux_images_dir}/linux-qemu"
            fi
            
        fi
    else
        info "Building Linux: make -j$(nproc) ARCH=${linux_arch} CROSS_COMPILE=${cross_compile} clean"
        make -j"$(nproc)" ARCH="${linux_arch}" CROSS_COMPILE="${cross_compile}" "clean"
        info "Removing ${linux_images_dir}/*"
        rm -rf "${linux_images_dir}"/* || true
    fi
}

arceos() {
    case "${ARCH}" in
        aarch64)
            local platform="aarch64-dyn"
            ;;
        riscv64)
            local platform="riscv64-qemu-virt"
            ;;
        x86_64)
            local platform="x86-pc"
            ;;
        *)
            die "Unsupported ArceOS architecture: ${ARCH}"
            ;;
    esac
    
    local arceos_images_dir="${PLATFORM_IMAGES_DIR}/arceos"
    info "Building ArceOS using tgoskits for platform: $platform -> $arceos_images_dir"

    bash "${SCRIPT_DIR}/../os/arceos.sh" "$platform" --images-dir "${arceos_images_dir}" --image-name "arceos-qemu" "$@"
}

qemu_ivc_arceos_config() {
    local package="$1"
    local config_dir="${BUILD_DIR}/qemu-${ARCH}-ivc"
    local config_path="${config_dir}/${package}.toml"

    mkdir -p "${config_dir}"
    cat > "${config_path}" <<'EOF'
features = ["arceos"]
log = "Warn"
EOF
    printf '%s\n' "${config_path}"
}

qemu_ivc_require_file() {
    local path="$1"
    local description="$2"

    [[ -f "${path}" ]] || die "Missing ${description}: ${path}"
}

qemu_ivc_build_arceos_guest() {
    local package="$1"
    local image_name="$2"
    local arceos_images_dir="${PLATFORM_IMAGES_DIR}/arceos"
    local image_path="${arceos_images_dir}/${image_name}"
    local config_path

    [[ "${ARCH}" == "aarch64" ]] || die "Axvisor IVC payload is currently only supported for qemu aarch64"
    if [[ -f "${image_path}" ]]; then
        info "Using existing Axvisor IVC ArceOS guest image: ${image_path}"
        return 0
    fi

    info "Building Axvisor IVC ArceOS guest: ${package} -> ${image_path}"
    config_path="$(qemu_ivc_arceos_config "${package}")"
    bash "${SCRIPT_DIR}/../os/arceos.sh" \
        aarch64-dyn \
        --images-dir "${arceos_images_dir}" \
        --image-name "${image_name}" \
        --package "${package}" \
        --target aarch64-unknown-none-softfloat \
        --config "${config_path}"

    qemu_ivc_require_file "${image_path}" "Axvisor IVC ArceOS guest image (${package})"
}

qemu_ivc_ensure_linux_guest() {
    local linux_image="${PLATFORM_IMAGES_DIR}/linux/linux-qemu"

    [[ "${ARCH}" == "aarch64" ]] || die "Axvisor IVC Linux guest is currently only supported for qemu aarch64"
    if [[ -f "${linux_image}" ]]; then
        info "Using existing qemu aarch64 Linux guest image: ${linux_image}"
        return 0
    fi

    linux
}

qemu_ivc_build_linux_tools() {
    local ivc_dir="${AXVISOR_TOOLS_SRC_DIR}/ivc"
    local overlay_dir="$1"
    local module="${ivc_dir}/kernel_driver/axvisor.ko"
    local subscriber="${ivc_dir}/subscribe-aarch64"
    local built_subscriber="${ivc_dir}/build/demo/subscribe"

    if [[ "${AXVISOR_TOOLS_SKIP_CHECKOUT}" == "1" ]]; then
        [[ -d "${AXVISOR_TOOLS_SRC_DIR}" ]] || die "AXVISOR_TOOLS_SRC_DIR does not exist: ${AXVISOR_TOOLS_SRC_DIR}"
        info "Using existing axvisor-tools source tree without checkout: ${AXVISOR_TOOLS_SRC_DIR}"
    else
        clone_repository "${AXVISOR_TOOLS_REPO_URL}" "${AXVISOR_TOOLS_SRC_DIR}"
        checkout_ref "${AXVISOR_TOOLS_SRC_DIR}" "${AXVISOR_TOOLS_REF}"
    fi

    if [[ ! -f "${subscriber}" ]]; then
        info "Building Axvisor IVC Linux subscriber demo"
        make -C "${ivc_dir}" \
            ARCH=arm64 \
            CROSS="${AARCH64_MUSL_CROSS:-aarch64-linux-musl-}" \
            demo
        [[ -f "${built_subscriber}" ]] || die "Linux IVC subscriber demo was not produced: ${built_subscriber}"
        cp -f "${built_subscriber}" "${subscriber}"
        chmod +x "${subscriber}"
    else
        info "Using existing Axvisor IVC Linux subscriber demo: ${subscriber}"
    fi

    info "Building Axvisor IVC Linux kernel module"
    make -C "${ivc_dir}/kernel_driver" \
        ARCH=arm64 \
        CROSS_COMPILE="${AARCH64_CROSS_COMPILE:-aarch64-linux-gnu-}" \
        KDIR="${LINUX_SRC_DIR}" \
        clean
    make -C "${ivc_dir}/kernel_driver" \
        ARCH=arm64 \
        CROSS_COMPILE="${AARCH64_CROSS_COMPILE:-aarch64-linux-gnu-}" \
        KDIR="${LINUX_SRC_DIR}"
    [[ -f "${module}" ]] || die "Linux IVC kernel module was not produced: ${module}"
    qemu_ivc_require_file "${subscriber}" "Linux IVC subscriber demo"

    mkdir -p "${overlay_dir}/root"
    cp -f "${module}" "${overlay_dir}/root/axvisor.ko"
    cp -f "${subscriber}" "${overlay_dir}/root/ivc-subscribe"
    chmod 0755 "${overlay_dir}/root/ivc-subscribe"

    qemu_ivc_require_file "${overlay_dir}/root/axvisor.ko" "rootfs overlay axvisor kernel module"
    qemu_ivc_require_file "${overlay_dir}/root/ivc-subscribe" "rootfs overlay Linux IVC subscriber demo"
}

qemu_ivc_validate_payloads() {
    local overlay_dir="$1"

    qemu_ivc_require_file "${PLATFORM_IMAGES_DIR}/arceos/arceos-ivc-publisher.bin" "Axvisor IVC ArceOS publisher image"
    qemu_ivc_require_file "${PLATFORM_IMAGES_DIR}/arceos/arceos-ivc-subscriber.bin" "Axvisor IVC ArceOS subscriber image"
    qemu_ivc_require_file "${overlay_dir}/root/axvisor.ko" "Axvisor IVC Linux kernel module overlay"
    qemu_ivc_require_file "${overlay_dir}/root/ivc-subscribe" "Axvisor IVC Linux subscriber overlay"
    success "Axvisor IVC rootfs payloads are ready"
}

qemu_ivc_validate_staged_payloads() {
    local stage_dir="$1"
    local overlay_dir="$2"

    qemu_ivc_require_file "${stage_dir}/guest/arceos/arceos-ivc-publisher.bin" "staged Axvisor IVC ArceOS publisher image"
    qemu_ivc_require_file "${stage_dir}/guest/arceos/arceos-ivc-subscriber.bin" "staged Axvisor IVC ArceOS subscriber image"
    qemu_ivc_require_file "${overlay_dir}/root/axvisor.ko" "staged Axvisor IVC Linux kernel module overlay"
    qemu_ivc_require_file "${overlay_dir}/root/ivc-subscribe" "staged Axvisor IVC Linux subscriber overlay"
}

qemu_prepare_ivc_payloads() {
    local overlay_dir="${BUILD_DIR}/qemu-${ARCH}-ivc-rootfs-overlay"

    [[ "${ARCH}" == "aarch64" ]] || return 0

    qemu_ivc_ensure_linux_guest

    rm -rf "${overlay_dir}"
    qemu_ivc_build_arceos_guest "arceos-ivc-publisher" "arceos-ivc-publisher.bin"
    qemu_ivc_build_arceos_guest "arceos-ivc-subscriber" "arceos-ivc-subscriber.bin"
    qemu_ivc_build_linux_tools "${overlay_dir}"
    qemu_ivc_validate_payloads "${overlay_dir}"
}

zephyr() {
    local zephyr_images_dir="${PLATFORM_IMAGES_DIR}/zephyr"

    if [[ "${ARCH}" != "aarch64" ]]; then
        die "Zephyr guest build is currently only supported for qemu aarch64"
    fi

    bash "${SCRIPT_DIR}/../os/zephyr.sh" qemu-aarch64 --images-dir "${zephyr_images_dir}" --image-name "zephyr-qemu" "$@"
}

freertos() {
    local freertos_images_dir="${PLATFORM_IMAGES_DIR}/freertos"

    if [[ "${ARCH}" != "aarch64" ]]; then
        die "FreeRTOS guest build is currently only supported for qemu aarch64"
    fi

    if [[ "$@" != *"clean"* ]]; then
        bash "${SCRIPT_DIR}/../os/freertos.sh" qemu-aarch64 --images-dir "${freertos_images_dir}" --image-name "freertos-qemu"
    else
        bash "${SCRIPT_DIR}/../os/freertos.sh" qemu-aarch64 clean --images-dir "${freertos_images_dir}" --image-name "freertos-qemu"
        rm -rf "${freertos_images_dir}" || true
    fi
}

qemu_rootfs_clean_outputs() {
    local rootfs_builder

    [[ ${#ROOTFS_BUILDERS[@]} -gt 0 ]] || return 0

    for rootfs_builder in "${ROOTFS_BUILDERS[@]}"; do
        case "${rootfs_builder}" in
            busybox)
                rm -f "${ROOT_DIR}/IMAGES/rootfs/initramfs-${ARCH}-busybox.cpio.gz"
                rm -f "${ROOT_DIR}/IMAGES/rootfs/rootfs-${ARCH}-busybox.img"
                ;;
            alpine)
                rm -f "${ROOT_DIR}/IMAGES/rootfs/rootfs-${ARCH}-alpine.img"
                ;;
            debian)
                rm -f "${ROOT_DIR}/IMAGES/rootfs/rootfs-${ARCH}-debian.img"
                ;;
            *)
                die "Unsupported rootfs builder: ${rootfs_builder} (supported: busybox, alpine, debian)"
                ;;
        esac
    done
}

qemu_rootfs_parse_args() {
    BUILD_ARGS=()
    ROOTFS_BUILD_ARGS=()
    ROOTFS_BUILDERS=()
    QEMU_OUTER_FREE_SIZE=""

    local builder
    local seen
    local -A rootfs_seen=()

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --rootfs)
                [[ $# -ge 2 ]] || die "--rootfs requires a value"
                IFS=',' read -r -a seen <<< "$2"
                for builder in "${seen[@]}"; do
                    [[ -n "${builder}" ]] || continue
                    case "${builder}" in
                        busybox|alpine|debian)
                            [[ -n "${rootfs_seen[${builder}]:-}" ]] && continue
                            rootfs_seen["${builder}"]=1
                            ROOTFS_BUILDERS+=("${builder}")
                            ;;
                        *)
                            die "Unsupported rootfs builder: ${builder} (supported: busybox, alpine, debian)"
                            ;;
                    esac
                done
                shift 2
                ;;
            --outer-tests|--guest-tests|--guest-free-size|--outer-free-size)
                [[ $# -ge 2 ]] || die "$1 requires a value"
                [[ "$2" != --* ]] || die "$1 requires a value"
                ROOTFS_BUILD_ARGS+=("$1" "$2")
                if [[ "$1" == "--outer-free-size" ]]; then
                    QEMU_OUTER_FREE_SIZE="$2"
                fi
                shift 2
                ;;
            *)
                BUILD_ARGS+=("$1")
                shift
                ;;
        esac
    done

    if [[ ${#ROOTFS_BUILDERS[@]} -gt 0 ]]; then
        return 0
    fi

    case "${OS}" in
        clean|help|-h|--help|"")
            return 0
            ;;
    esac

    if [[ "${ARCH}" == "loongarch64" ]]; then
        ROOTFS_BUILDERS=(busybox alpine)
    else
        ROOTFS_BUILDERS=(busybox alpine debian)
    fi
}

qemu_rootfs_build_step() {
    local rootfs_builder="$1"

    bash "${SCRIPT_DIR}/../rootfs/${rootfs_builder}.sh" \
        "${ARCH}" --out_dir "${ROOT_DIR}/IMAGES/rootfs" "${ROOTFS_BUILD_ARGS[@]}"
}

qemu_rootfs_busybox_step() { qemu_rootfs_build_step busybox; }
qemu_rootfs_alpine_step() { qemu_rootfs_build_step alpine; }
qemu_rootfs_debian_step() { qemu_rootfs_build_step debian; }

qemu_has_help_arg() {
    local arg

    for arg in "$@"; do
        case "${arg}" in
            help|-h|--help)
                return 0
                ;;
        esac
    done
    return 1
}

qemu_rootfs_inject_platform_dir() (
    local guest_dir="${PLATFORM_IMAGES_DIR}"
    local stage_dir
    local ivc_overlay_dir="${BUILD_DIR}/qemu-${ARCH}-ivc-rootfs-overlay"
    local rootfs_builder
    local has_aarch64_alpine=0
    local empty_overlay_dir
    local alpine_stage_dir=""
    local builder_guest_dir
    local protected_basename
    local outer_image
    local outer_reserve="${QEMU_OUTER_FREE_SIZE:-256M}"

    [[ ${#ROOTFS_BUILDERS[@]} -gt 0 ]] || return 0

    for rootfs_builder in "${ROOTFS_BUILDERS[@]}"; do
        if [[ "${ARCH}" == "aarch64" && "${rootfs_builder}" == "alpine" ]]; then
            has_aarch64_alpine=1
            break
        fi
    done

    if [[ ! -d "${guest_dir}" && "${has_aarch64_alpine}" -ne 1 ]]; then
        warn "No guest payload was produced for qemu ${ARCH}, skipping rootfs injection"
        return 0
    fi

    stage_dir="$(mktemp -d "${BUILD_DIR}/qemu-rootfs-${ARCH}.XXXXXX")"
    trap 'rm -rf "${stage_dir}"; [[ -z "${alpine_stage_dir:-}" ]] || rm -rf "${alpine_stage_dir}"' EXIT
    empty_overlay_dir="${stage_dir}/empty-overlay"
    mkdir -p "${empty_overlay_dir}"
    if [[ -d "${guest_dir}" ]]; then
        rootfs_stage_guest_tree "${stage_dir}" "${guest_dir}"
    else
        mkdir -p "${stage_dir}/guest"
    fi
    # QEMU owns this staging copy. Build outputs commonly carry nanosecond
    # timestamps, while the verified debugfs injector intentionally accepts
    # only whole-second metadata. Normalize the private copy, not IMAGES/.
    _rootfs_builder_normalize_overlay_seconds "${stage_dir}" || return 1

    if [[ "${has_aarch64_alpine}" -eq 1 ]]; then
        qemu_prepare_ivc_payloads
        alpine_stage_dir="$(mktemp -d "${BUILD_DIR}/qemu-rootfs-${ARCH}-alpine.XXXXXX")"
        rootfs_stage_guest_tree "${alpine_stage_dir}" "${guest_dir}"
        qemu_ivc_validate_staged_payloads "${alpine_stage_dir}" "${ivc_overlay_dir}"
        _rootfs_builder_normalize_overlay_seconds "${alpine_stage_dir}" || return 1
        _rootfs_builder_normalize_overlay_seconds "${ivc_overlay_dir}" || return 1
    fi

    # Reject every protected nested-image basename before touching any output.
    for rootfs_builder in "${ROOTFS_BUILDERS[@]}"; do
        protected_basename="rootfs-${ARCH}-${rootfs_builder}.img"
        if [[ -e "${stage_dir}/guest/${protected_basename}" || -L "${stage_dir}/guest/${protected_basename}" ]]; then
            die "Platform payload collides with protected nested image basename: ${protected_basename}"
        fi
        if [[ -n "${alpine_stage_dir}" && ( -e "${alpine_stage_dir}/guest/${protected_basename}" || -L "${alpine_stage_dir}/guest/${protected_basename}" ) ]]; then
            die "Platform payload collides with protected nested image basename: ${protected_basename}"
        fi
    done

    for rootfs_builder in "${ROOTFS_BUILDERS[@]}"; do
        protected_basename="rootfs-${ARCH}-${rootfs_builder}.img"
        outer_image="${ROOT_DIR}/IMAGES/rootfs/${protected_basename}"
        builder_guest_dir="${stage_dir}/guest"
        if [[ "${ARCH}" == "aarch64" && "${rootfs_builder}" == "alpine" ]]; then
            builder_guest_dir="${alpine_stage_dir}/guest"
        fi
        case "${rootfs_builder}" in
            busybox)
                _rootfs_builder_normalize_overlay_seconds "${builder_guest_dir}" || return 1
                rootfs_inject_guest_stage "${ROOT_DIR}/IMAGES/rootfs/initramfs-${ARCH}-busybox.cpio.gz" "${builder_guest_dir}" || return 1
                # Reading the staging tree while repacking cpio can advance
                # atime with nanosecond precision. Normalize this private copy
                # again before the strict ext4 payload validation.
                _rootfs_builder_normalize_overlay_seconds "${builder_guest_dir}" || return 1
                rootfs_inject_outer_payload_atomic "${outer_image}" "${builder_guest_dir}" \
                    "${empty_overlay_dir}" "${protected_basename}" "${outer_reserve}" || return 1
                ;;
            alpine)
                _rootfs_builder_normalize_overlay_seconds "${builder_guest_dir}" || return 1
                if [[ "${ARCH}" == "aarch64" ]]; then
                    _rootfs_builder_normalize_overlay_seconds "${ivc_overlay_dir}" || return 1
                    rootfs_inject_outer_payload_atomic "${outer_image}" "${builder_guest_dir}" \
                        "${ivc_overlay_dir}" "${protected_basename}" "${outer_reserve}" || return 1
                else
                    rootfs_inject_outer_payload_atomic "${outer_image}" "${builder_guest_dir}" \
                        "${empty_overlay_dir}" "${protected_basename}" "${outer_reserve}" || return 1
                fi
                ;;
            debian)
                _rootfs_builder_normalize_overlay_seconds "${builder_guest_dir}" || return 1
                rootfs_inject_outer_payload_atomic "${outer_image}" "${builder_guest_dir}" \
                    "${empty_overlay_dir}" "${protected_basename}" "${outer_reserve}" || return 1
                ;;
            *)
                die "Unsupported rootfs builder: ${rootfs_builder} (supported: busybox, alpine, debian)"
                ;;
        esac
        success "Root filesystem injection completed: ${rootfs_builder}"
    done

    trap - EXIT
    rm -rf "${stage_dir}"
    [[ -z "${alpine_stage_dir}" ]] || rm -rf "${alpine_stage_dir}"
)

qemu_build_os_and_rootfs() {
    local action="$1"
    shift
    local os_steps=("$@")
    local rootfs_builder
    local action_log_dir
    action_log_dir="$(new_log_dir "platform" "qemu" "${action}-${ARCH}")"
    local summary_log="${action_log_dir}/summary.log"
    local parallel_steps=("${os_steps[@]}")

    for rootfs_builder in "${ROOTFS_BUILDERS[@]}"; do
        parallel_steps+=("qemu_rootfs_${rootfs_builder}_step")
    done

    if ! PARALLEL_LOG_DIR="${action_log_dir}" \
         PARALLEL_DEFER_COMPLETION=1 \
             run_parallel_functions "${action}-${ARCH}" "${parallel_steps[@]}" -- "${BUILD_ARGS[@]}"; then
        printf '[%s] COMPLETE %s-%s: parallel build failed\n' "$(date '+%F %T')" "${action}" "${ARCH}" | tee -a "${summary_log}"
        printf '[%s] Summary log: %s\n' "$(date '+%F %T')" "${summary_log}" | tee -a "${summary_log}"
        return 1
    fi

    qemu_rootfs_inject_platform_dir
    printf '[%s] COMPLETE %s-%s: all steps finished successfully\n' "$(date '+%F %T')" "${action}" "${ARCH}" | tee -a "${summary_log}"
    printf '[%s] Summary log: %s\n' "$(date '+%F %T')" "${summary_log}" | tee -a "${summary_log}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    LOG_CREATE_DEFAULT_FILE="${LOG_CREATE_DEFAULT_FILE:-0}"
    source "${SCRIPT_DIR}/../lib/utils.sh"
    source "${SCRIPT_DIR}/../lib/rootfs.sh"
    source "${SCRIPT_DIR}/../lib/rootfs-compose.sh"
    cmd="${1:-}"
    shift 1 || true
    case "${cmd}" in
        ""|help|-h|--help)
            usage
            exit 0
            ;;
        aarch64|riscv64|x86_64|loongarch64)
            ARCH="$cmd"
            ROOTFS_ARCH="${ARCH}"
            PLATFORM_IMAGES_DIR="${ROOT_DIR}/IMAGES/qemu-${ARCH}"
            if [[ $# -eq 0 || "${1:-}" == "help" || "${1:-}" == "-h" || "${1:-}" == "--help" || "${1:-}" == --* ]]; then
                QEMU_ARCH="${ARCH}" usage
                exit 0
            fi
            OS="$1"
            shift 1 || true
            qemu_rootfs_parse_args "$@"
            if qemu_has_help_arg "${BUILD_ARGS[@]}"; then
                QEMU_ARCH="${ARCH}" usage
                exit 0
            fi
            case "${OS}" in
                linux)
                    qemu_build_os_and_rootfs "linux" linux
                    ;;
                arceos)
                    qemu_build_os_and_rootfs "arceos" arceos
                    ;;
                zephyr)
                    [[ "${ARCH}" == "aarch64" ]] || die "Zephyr guest build is currently only supported for qemu aarch64"
                    qemu_build_os_and_rootfs "zephyr" zephyr
                    ;;
                freertos)
                    [[ "${ARCH}" == "aarch64" ]] || die "FreeRTOS guest build is currently only supported for qemu aarch64"
                    qemu_build_os_and_rootfs "freertos" freertos
                    ;;
                all)
                    qemu_steps=(linux)
                    if [[ "${ARCH}" != "loongarch64" ]]; then
                        qemu_steps+=(arceos)
                    fi
                    if [[ "${ARCH}" == "aarch64" ]]; then
                        qemu_steps+=(zephyr freertos)
                    fi
                    qemu_build_os_and_rootfs "all" "${qemu_steps[@]}"
                    ;;
                clean)
                    qemu_steps=(linux)
                    if [[ "${ARCH}" != "loongarch64" ]]; then
                        qemu_steps+=(arceos)
                    fi
                    if [[ "${ARCH}" == "aarch64" ]]; then
                        qemu_steps+=(zephyr freertos)
                    fi
                    run_parallel_functions "clean-${ARCH}" "${qemu_steps[@]}" -- clean
                    qemu_rootfs_clean_outputs
                    ;;
                *)
                    die "Unknown os: ${OS} (supported: linux, arceos, zephyr, freertos, all)"
                    ;;
            esac
            ;;
        all)
            if [[ $# -eq 0 || "${1:-}" == "help" || "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
                QEMU_ARCH="all" usage
                exit 0
            fi

            if [[ "${1:-}" == --* ]]; then
                OS="all"
            else
                OS="$1"
                shift 1 || true
            fi

            for arch in aarch64 riscv64 x86_64 loongarch64; do
                "$0" "$arch" "${OS}" "$@" || { echo "[ERROR] $arch build failed" >&2; exit 1; }
            done
            ;;
        clean)
            for arch in aarch64 riscv64 x86_64 loongarch64; do
                "$0" "$arch" "clean" || { echo "[ERROR] $arch build failed" >&2; exit 1; }
            done
            ;;
        *)
        die "Unknown command: $cmd" >&2
        ;;
    esac
fi
