#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)
ROOT_DIR=$(cd "${SCRIPT_DIR}/../.." && pwd -P)
BUILD_DIR="$(cd "${ROOT_DIR}" && mkdir -p "build" && cd "build" && pwd -P)"

source "${SCRIPT_DIR}/../lib/utils.sh"
source "${SCRIPT_DIR}/../lib/rootfs.sh"

# Repository URLs

# Source directories
LINUX_REPO_URL="https://github.com/torvalds/linux.git"
LINUX_REF="74fe02ce122a6103f207d29fafc8b3a53de6abaf"
LINUX_SRC_DIR="${BUILD_DIR}/qemu_linux"
LINUX_PATCH_DIR="${ROOT_DIR}/patches/qemu"
ROOTFS_BUILDERS=()
BUILD_ARGS=()
PLATFORM_IMAGES_DIR=""

# Display help information
usage() {
    local usage_arch="${QEMU_ARCH:-}"

    printf 'Build supported OS for QEMU with rootfs support\n'
    printf '\n'
    printf 'Usage:\n'
    if [[ -n "${usage_arch}" ]]; then
        if [[ "${usage_arch}" == "all" ]]; then
            printf '  ./build.sh platform qemu [os] [options]\n'
        else
            printf '  ./build.sh platform qemu-%s [os] [options]\n' "${usage_arch}"
        fi
    else
        printf '  scripts/qemu.sh <command> <os> [options]\n'
        printf '\n'
        printf 'Commands:\n'
        printf '  aarch64                           Build all OS targets for AArch64 architecture\n'
        printf '  x86_64                            Build all OS targets for x86_64 architecture\n'
        printf '  riscv64                           Build all OS targets for RISC-V architecture\n'
        printf '  loongarch64                       Build all OS targets for LoongArch64 architecture\n'
        printf '  all                               Build all supported architectures and OS targets\n'
        printf '  help, -h, --help                  Display this help information\n'
        printf '  clean                             Clean build output artifacts\n'
    fi
    printf '\n'
    printf 'OS Targets:\n'
    printf '  linux                             Build the Linux OS\n'
    printf '  arceos                            Build the ArceOS OS\n'
    printf '  nimbos                            Build the NimbOS OS\n'
    printf '  zephyr                            Build the Zephyr guest image (aarch64 only)\n'
    printf '  freertos                          Build the FreeRTOS guest image (aarch64 only)\n'
    printf '  all                               Build all OS targets (default)\n'
    printf '  clean                             Clean build output artifacts\n'
    printf '\n'
    printf 'Options:\n'
    printf '  Optional, all options will be directly passed to the specific OS build script\n'
    printf '  --rootfs <list>                   Override default rootfs builders (busybox,alpine,debian)\n'
    printf '                                    Default for loongarch64 is alpine\n'
    printf '\n'
    printf 'Rootfs Packaging:\n'
    printf '  * Rootfs is generated by default for build commands.\n'
    printf '  * Rootfs is not generated for help or clean commands.\n'
    printf '  * Build outputs from all selected OS targets are staged together into /guest/<os>/ inside one rootfs.\n'
    printf '  * Generated rootfs artifacts are stored directly under IMAGES/rootfs.\n'
    printf '\n'
    printf 'Examples:\n'
    if [[ -n "${usage_arch}" ]]; then
        if [[ "${usage_arch}" == "all" ]]; then
            printf '  ./build.sh platform qemu linux\n'
            printf '  ./build.sh platform qemu all --rootfs busybox,alpine,debian\n'
        else
            printf '  ./build.sh platform qemu-%s linux\n' "${usage_arch}"
            if [[ "${usage_arch}" == "loongarch64" ]]; then
                printf '  ./build.sh platform qemu-%s all --rootfs alpine\n' "${usage_arch}"
            else
                printf '  ./build.sh platform qemu-%s all --rootfs busybox,alpine,debian\n' "${usage_arch}"
            fi
        fi
    else
        printf '  scripts/qemu.sh aarch64 linux     # Build ARM64 Linux\n'
        printf '  scripts/qemu.sh x86_64 arceos     # Build x86_64 ArceOS\n'
        printf '  scripts/qemu.sh riscv64 nimbos    # Build RISC-V NimbOS\n'
        printf '  scripts/qemu.sh loongarch64 linux # Build LoongArch64 Linux\n'
        printf '  scripts/qemu.sh aarch64 all --rootfs busybox,alpine,debian\n'
        printf '  scripts/qemu.sh riscv64 all       # Build all OS targets for RISC-V\n'
    fi
}

linux() {
    local linux_images_dir="${PLATFORM_IMAGES_DIR}/linux"

    info "Cloning ${ARCH} Linux source repository $LINUX_REPO_URL"
    clone_repository "$LINUX_REPO_URL" "$LINUX_SRC_DIR"
    info "Checking out ${ARCH} Linux ref ${LINUX_REF}"
    checkout_ref "$LINUX_SRC_DIR" "$LINUX_REF"

    info "Applying patches..."
    apply_patches "$LINUX_PATCH_DIR" "$LINUX_SRC_DIR"

    info "Starting to build ${ARCH} Linux OS..."
    local commands=("$@")
    case "${ARCH}" in
        aarch64)
            local linux_arch="arm64"
            local cross_compile="${AARCH64_CROSS_COMPILE:-aarch64-linux-gnu-}"
            local defconfig="defconfig"
            local kimg_subpath="arch/arm64/boot/Image"
            ;;
        riscv64)
            local linux_arch="riscv"
            local cross_compile="${RISCV64_CROSS_COMPILE:-riscv64-linux-gnu-}"
            local defconfig="defconfig"
            local kimg_subpath="arch/riscv/boot/Image"
            ;;
        x86_64)
            local linux_arch="x86"
            local cross_compile="${X86_CROSS_COMPILE:-}"
            local defconfig="x86_64_defconfig"
            local kimg_subpath="arch/x86/boot/bzImage"
            ;;
        loongarch64)
            local linux_arch="loongarch"
            local cross_compile="${LOONGARCH64_CROSS_COMPILE:-loongarch64-linux-gnu-}"
            local defconfig="loongson64_defconfig"
            local kimg_subpath="arch/loongarch/boot/vmlinuz.efi"
            ;;
        *)
            die "Unsupported Linux architecture: ${ARCH}"
            ;;
    esac
    
    pushd "${LINUX_SRC_DIR}" >/dev/null

    # info "Cleaning Linux: make distclean"
    # make distclean || true

    if [[ "$@" != *"clean"* ]]; then
        if [[ ${#commands[@]} -eq 0 ]] || [[ "${commands[0]}" == "all" ]]; then
            info "Configuring Linux: make ARCH=${linux_arch} CROSS_COMPILE=${cross_compile} ${defconfig}"
            make ARCH="${linux_arch}" CROSS_COMPILE="${cross_compile}" "${defconfig}"
        fi
        
        info "Building Linux: make -j$(nproc) ARCH=${linux_arch} CROSS_COMPILE=${cross_compile} ${commands[@]}"
        make -j"$(nproc)" ARCH="${linux_arch}" CROSS_COMPILE="${cross_compile}" "${commands[@]}"
        
        popd >/dev/null

        # If it's a full build, copy the image and create the root filesystem
        if [[ ${#commands[@]} -eq 0 ]] || [[ "${commands[0]}" == "all" ]]; then
            mkdir -p "${linux_images_dir}"
            KIMG_PATH="${LINUX_SRC_DIR}/${kimg_subpath}"
            [[ -f "${KIMG_PATH}" ]] || die "Kernel image not found: ${KIMG_PATH}"
            info "Copying image: ${KIMG_PATH} -> ${linux_images_dir}/linux-qemu"
            cp -f "${KIMG_PATH}" "${linux_images_dir}/linux-qemu"
            
        fi
    else
        info "Building Linux: make -j$(nproc) ARCH=${linux_arch} CROSS_COMPILE=${cross_compile} clean"
        make -j"$(nproc)" ARCH="${linux_arch}" CROSS_COMPILE="${cross_compile}" "clean"
        info "Removing ${linux_images_dir}/*"
        rm -rf "${linux_images_dir}"/* || true
    fi
}

arceos() {
    case "${ARCH}" in
        aarch64)
            local platform="aarch64-dyn"
            ;;
        riscv64)
            local platform="riscv64-qemu-virt"
            ;;
        x86_64)
            local platform="x86-pc"
            ;;
        *)
            die "Unsupported ArceOS architecture: ${ARCH}"
            ;;
    esac
    
    local arceos_images_dir="${PLATFORM_IMAGES_DIR}/arceos"
    info "Building ArceOS using tgoskits for platform: $platform -> $arceos_images_dir"

    bash "${SCRIPT_DIR}/../os/arceos.sh" "$platform" --images-dir "${arceos_images_dir}" --image-name "arceos-qemu" "$@"
}

nimbos() {
    local nimbos_images_dir="${PLATFORM_IMAGES_DIR}/nimbos"

    bash "${SCRIPT_DIR}/../os/nimbos.sh" "$ARCH" --images-dir "${nimbos_images_dir}" --image-name "nimbos-qemu" "$@"

    if [[ "$@" == *"clean"* ]]; then
        rm -rf "${nimbos_images_dir}" || true
    fi
}

zephyr() {
    local zephyr_images_dir="${PLATFORM_IMAGES_DIR}/zephyr"

    if [[ "${ARCH}" != "aarch64" ]]; then
        die "Zephyr guest build is currently only supported for qemu aarch64"
    fi

    bash "${SCRIPT_DIR}/../os/zephyr.sh" qemu-aarch64 --images-dir "${zephyr_images_dir}" --image-name "zephyr-qemu" "$@"
}

freertos() {
    local freertos_images_dir="${PLATFORM_IMAGES_DIR}/freertos"

    if [[ "${ARCH}" != "aarch64" ]]; then
        die "FreeRTOS guest build is currently only supported for qemu aarch64"
    fi

    if [[ "$@" != *"clean"* ]]; then
        bash "${SCRIPT_DIR}/../os/freertos.sh" qemu-aarch64 --images-dir "${freertos_images_dir}" --image-name "freertos-qemu"
    else
        bash "${SCRIPT_DIR}/../os/freertos.sh" qemu-aarch64 clean --images-dir "${freertos_images_dir}" --image-name "freertos-qemu"
        rm -rf "${freertos_images_dir}" || true
    fi
}

qemu_rootfs_clean_outputs() {
    local rootfs_builder

    [[ ${#ROOTFS_BUILDERS[@]} -gt 0 ]] || return 0

    for rootfs_builder in "${ROOTFS_BUILDERS[@]}"; do
        case "${rootfs_builder}" in
            busybox)
                rm -f "${ROOT_DIR}/IMAGES/rootfs/initramfs-${ARCH}-busybox.cpio.gz"
                rm -f "${ROOT_DIR}/IMAGES/rootfs/rootfs-${ARCH}-busybox.img"
                ;;
            alpine)
                rm -f "${ROOT_DIR}/IMAGES/rootfs/rootfs-${ARCH}-alpine.img"
                ;;
            debian)
                rm -f "${ROOT_DIR}/IMAGES/rootfs/rootfs-${ARCH}-debian.img"
                ;;
            *)
                die "Unsupported rootfs builder: ${rootfs_builder} (supported: busybox, alpine, debian)"
                ;;
        esac
    done
}

qemu_rootfs_parse_args() {
    BUILD_ARGS=()
    ROOTFS_BUILDERS=()

    local builder
    local seen
    local -A rootfs_seen=()

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --rootfs)
                [[ $# -ge 2 ]] || die "--rootfs requires a value"
                IFS=',' read -r -a seen <<< "$2"
                for builder in "${seen[@]}"; do
                    [[ -n "${builder}" ]] || continue
                    case "${builder}" in
                        busybox|alpine|debian)
                            [[ -n "${rootfs_seen[${builder}]:-}" ]] && continue
                            rootfs_seen["${builder}"]=1
                            ROOTFS_BUILDERS+=("${builder}")
                            ;;
                        *)
                            die "Unsupported rootfs builder: ${builder} (supported: busybox, alpine, debian)"
                            ;;
                    esac
                done
                shift 2
                ;;
            *)
                BUILD_ARGS+=("$1")
                shift
                ;;
        esac
    done

    if [[ ${#ROOTFS_BUILDERS[@]} -gt 0 ]]; then
        return 0
    fi

    case "${OS}" in
        clean|help|-h|--help|"")
            return 0
            ;;
    esac

    if [[ "${ARCH}" == "loongarch64" ]]; then
        ROOTFS_BUILDERS=(alpine)
    else
        ROOTFS_BUILDERS=(busybox alpine debian)
    fi
}

qemu_rootfs_build_from_platform_dir() {
    local guest_dir="${PLATFORM_IMAGES_DIR}"
    local stage_dir
    local rootfs_builder
    local rootfs_script

    [[ ${#ROOTFS_BUILDERS[@]} -gt 0 ]] || return 0
    if [[ ! -d "${guest_dir}" ]]; then
        warn "No guest payload was produced for qemu ${ARCH}, skipping rootfs generation"
        return 0
    fi

    stage_dir="$(mktemp -d "${BUILD_DIR}/qemu-rootfs-${ARCH}.XXXXXX")"
    trap 'rm -rf "${stage_dir}"' RETURN
    rootfs_stage_guest_tree "${stage_dir}" "${guest_dir}"

    for rootfs_builder in "${ROOTFS_BUILDERS[@]}"; do
        rootfs_script="${SCRIPT_DIR}/../rootfs/${rootfs_builder}.sh"
        [[ -f "${rootfs_script}" ]] || die "Root filesystem script does not exist: ${rootfs_script}"

        info "Creating root filesystem: ${rootfs_script} -> IMAGES/rootfs"
        case "${rootfs_builder}" in
            busybox|alpine|debian)
                bash "${rootfs_script}" "${ARCH}" --out_dir "${ROOT_DIR}/IMAGES/rootfs" --guest "${stage_dir}/guest"
                ;;
            *)
                die "Unsupported rootfs builder: ${rootfs_builder} (supported: busybox, alpine, debian)"
                ;;
        esac
        success "Root filesystem creation completed"
    done

    trap - RETURN
    rm -rf "${stage_dir}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    cmd="${1:-}"
    shift 1 || true
    case "${cmd}" in
        ""|help|-h|--help)
            usage
            exit 0
            ;;
        aarch64|riscv64|x86_64|loongarch64)
            ARCH="$cmd"
            ROOTFS_ARCH="${ARCH}"
            PLATFORM_IMAGES_DIR="${ROOT_DIR}/IMAGES/qemu-${ARCH}"
            if [[ $# -eq 0 || "${1:-}" == "help" || "${1:-}" == "-h" || "${1:-}" == "--help" || "${1:-}" == --* ]]; then
                QEMU_ARCH="${ARCH}" usage
                exit 0
            fi
            OS="$1"
            shift 1 || true
            qemu_rootfs_parse_args "$@"
            case "${OS}" in
                linux)
                    linux "${BUILD_ARGS[@]}"
                    ;;
                arceos)
                    arceos "${BUILD_ARGS[@]}"
                    ;;
                nimbos)
                    nimbos "${BUILD_ARGS[@]}"
                    ;;
                zephyr)
                    zephyr "${BUILD_ARGS[@]}"
                    ;;
                freertos)
                    freertos "${BUILD_ARGS[@]}"
                    ;;
                all)
                    linux "${BUILD_ARGS[@]}"
                    if [[ "${ARCH}" != "loongarch64" ]]; then
                        arceos "${BUILD_ARGS[@]}"
                    fi
                    if [[ "${ARCH}" != "loongarch64" ]]; then
                        nimbos "${BUILD_ARGS[@]}"
                    fi
                    if [[ "${ARCH}" == "aarch64" ]]; then
                        zephyr "${BUILD_ARGS[@]}"
                        freertos "${BUILD_ARGS[@]}"
                    fi
                    ;;
                clean)
                    linux "clean"
                    arceos "clean"
                    if [[ "${ARCH}" != "loongarch64" ]]; then
                        nimbos "clean"
                    fi
                    if [[ "${ARCH}" == "aarch64" ]]; then
                        zephyr "clean"
                        freertos "clean"
                    fi
                    qemu_rootfs_clean_outputs
                    ;;
                *)
                    die "Unknown os: ${OS} (supported: linux, arceos, nimbos, zephyr, freertos, all)"
                    ;;
            esac
            if [[ "${OS}" != "clean" ]]; then
                qemu_rootfs_build_from_platform_dir
            fi
            ;;
        all)
            if [[ $# -eq 0 || "${1:-}" == "help" || "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
                QEMU_ARCH="all" usage
                exit 0
            fi

            if [[ "${1:-}" == --* ]]; then
                OS="all"
            else
                OS="$1"
                shift 1 || true
            fi

            for arch in aarch64 riscv64 x86_64 loongarch64; do
                "$0" "$arch" "${OS}" "$@" || { echo "[ERROR] $arch build failed" >&2; exit 1; }
            done
            ;;
        clean)
            for arch in aarch64 riscv64 x86_64 loongarch64; do
                "$0" "$arch" "clean" || { echo "[ERROR] $arch build failed" >&2; exit 1; }
            done
            ;;
        *)
        die "Unknown command: $cmd" >&2
        ;;
    esac
fi
